package Pantallas.moduloProductos;

import DTOs.IngredienteViejoDTO;

/**
 *
 * @author daniel
 */
public class Ingredientes extends javax.swing.JPanel {

    private IngredienteViejoDTO ingrediente;
    
    /**
     * Creates new form Ingredientes
     */
    public Ingredientes(IngredienteViejoDTO ingrediente) {
        initComponents();
        this.ingrediente = ingrediente;
        txfNombre.setText(ingrediente.getNombre());
        txfMedida.setText(ingrediente.getUnidadMedida().toString());
        txfCantidad.setText("1");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfNombre = new javax.swing.JTextField();
        txfCantidad = new javax.swing.JTextField();
        txfMedida = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(646, 29));
        setMinimumSize(new java.awt.Dimension(646, 29));
        setName(""); // NOI18N

        txfNombre.setEditable(false);
        txfNombre.setBackground(new java.awt.Color(217, 217, 217));
        txfNombre.setText("a");
        txfNombre.setBorder(null);
        txfNombre.setOpaque(false);

        txfCantidad.setEditable(false);
        txfCantidad.setBackground(new java.awt.Color(217, 217, 217));
        txfCantidad.setText("a");
        txfCantidad.setBorder(null);
        txfCantidad.setOpaque(false);

        txfMedida.setEditable(false);
        txfMedida.setBackground(new java.awt.Color(217, 217, 217));
        txfMedida.setText("a");
        txfMedida.setBorder(null);
        txfMedida.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(236, 34, 31));
        jButton1.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txfMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField txfCantidad;
    private javax.swing.JTextField txfMedida;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
