package Pantallas.moduloProductos;

import DTOs.IngredienteViejoDTO;
import DTOs.ProductoIngredienteViejoDTO;

/**
 *
 * @author daniel
 */
public class PnlIngredientes extends javax.swing.JPanel {

    /**
     * Creates new form PnlIngredientes
     */
    public PnlIngredientes(ProductoIngredienteViejoDTO productoIngrediente) {
        initComponents();
        IngredienteViejoDTO ingrediente = productoIngrediente.getIngrediente();
        
        txfNombre.setText(ingrediente.getNombre());
        txfMedida.setText(ingrediente.getUnidadMedida().toString());
        txfCantidad.setText(productoIngrediente.getCantidadRequerida().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfNombre = new javax.swing.JTextField();
        txfMedida = new javax.swing.JTextField();
        txfCantidad = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(609, 24));
        setMinimumSize(new java.awt.Dimension(609, 24));

        txfNombre.setEditable(false);
        txfNombre.setBackground(new java.awt.Color(217, 217, 217));
        txfNombre.setText("a");
        txfNombre.setBorder(null);
        txfNombre.setOpaque(false);

        txfMedida.setEditable(false);
        txfMedida.setBackground(new java.awt.Color(217, 217, 217));
        txfMedida.setText("a");
        txfMedida.setBorder(null);
        txfMedida.setOpaque(false);

        txfCantidad.setEditable(false);
        txfCantidad.setBackground(new java.awt.Color(217, 217, 217));
        txfCantidad.setText("a");
        txfCantidad.setBorder(null);
        txfCantidad.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(txfMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txfCantidad;
    private javax.swing.JTextField txfMedida;
    private javax.swing.JTextField txfNombre;
    // End of variables declaration//GEN-END:variables
}
