package comandas;

import DTOs.MesaViejaDTO;
import control.ControlFlujoPantallas;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author daniel
 */
public class PnlMesa extends javax.swing.JPanel {

    private MesaViejaDTO mesa;
    
    /**
     * Creates new form PnlMesa
     */
    public PnlMesa(MesaViejaDTO mesa) {
        initComponents();
        this.mesa = mesa;
        
        txfNumero.setText(String.valueOf(mesa.getNumero()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAñadir = new javax.swing.JButton();
        txfNumero = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(786, 28));
        setMinimumSize(new java.awt.Dimension(786, 28));
        setPreferredSize(new java.awt.Dimension(786, 28));

        btnAñadir.setBackground(new java.awt.Color(44, 165, 0));
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        txfNumero.setEditable(false);
        txfNumero.setBackground(new java.awt.Color(217, 217, 217));
        txfNumero.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfNumero.setText("a");
        txfNumero.setBorder(null);
        txfNumero.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 644, Short.MAX_VALUE)
                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadir)
                    .addComponent(txfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        ControlFlujoPantallas control = ControlFlujoPantallas.getInstancia();
        control.agregarMesaAComanda(mesa);
        control.abrirFrmProductosDisponibles();
        
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_btnAñadirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JTextField txfNumero;
    // End of variables declaration//GEN-END:variables
}
