package comandas;

import DTOs.ProductoViejoDTO;
import control.ControlFlujoPantallas;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author daniel
 */
public class PnlProductoDisponible extends javax.swing.JPanel {

    private ProductoViejoDTO producto;
    
    /**
     * Creates new form PnlProductoDisponible
     */
    public PnlProductoDisponible(ProductoViejoDTO producto) {
        initComponents();
        this.producto = producto;
        
        txfNombre.setText(producto.getNombre());
        txfTipo.setText(producto.getTipo().toString());
        txfPrecio.setText(producto.getPrecio().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txfNombre = new javax.swing.JTextField();
        txfPrecio = new javax.swing.JTextField();
        txfTipo = new javax.swing.JTextField();
        btnAñadir = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(786, 28));
        setMinimumSize(new java.awt.Dimension(786, 28));
        setPreferredSize(new java.awt.Dimension(786, 28));

        txfNombre.setEditable(false);
        txfNombre.setBackground(new java.awt.Color(217, 217, 217));
        txfNombre.setText("Hamburguesa con carne");
        txfNombre.setBorder(null);
        txfNombre.setOpaque(false);

        txfPrecio.setEditable(false);
        txfPrecio.setBackground(new java.awt.Color(217, 217, 217));
        txfPrecio.setText("a");
        txfPrecio.setBorder(null);
        txfPrecio.setOpaque(false);

        txfTipo.setEditable(false);
        txfTipo.setBackground(new java.awt.Color(217, 217, 217));
        txfTipo.setText("a");
        txfTipo.setBorder(null);
        txfTipo.setOpaque(false);

        btnAñadir.setBackground(new java.awt.Color(44, 165, 0));
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(txfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btnAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAñadir)
                .addComponent(txfTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        ControlFlujoPantallas.getInstancia().abrirFrmProducto(producto);
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
    }//GEN-LAST:event_btnAñadirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfPrecio;
    private javax.swing.JTextField txfTipo;
    // End of variables declaration//GEN-END:variables
}
